controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["wheel_left_joint"]
    right_wheel_names: ["wheel_right_joint"]
    wheel_separation: 0.5 
    wheel_radius: 0.1     
    publish_rate: 50.0
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    enable_odom_tf: true

my_robot_hardware:
  ros__parameters:
    hardware_plugin: "diff_drive_hw_interface/DiffDriveHWInterface"
