controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    diffbot_base_controller:
      type: diff_drive_controller/DiffDriveController

diffbot_base_controller:
  ros__parameters:
    left_wheel_names: ["left_front_wheel_joint", "left_rear_wheel_joint"]
    right_wheel_names: ["right_front_wheel_joint", "right_rear_wheel_joint"]
    wheel_separation: 0.10
    wheel_radius: 0.015
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    open_loop: false
    enable_odom_tf: false  # Handled by robot_localization
    cmd_vel_timeout: 0.5
    linear.x.max_velocity: 1.0
    linear.x.max_acceleration: 0.5
    angular.z.max_velocity: 1.0
    angular.z.max_acceleration: 0.5
